server:
  port: 8000

spring:
  application:
    name: boki-eureka

eureka:
  instance:
    instance-id: boki-eureka
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    fetch-registry: false
    registerWithEureka: false
