server:
  port: 8000

spring:
  application:
    name: boki-eureka
  security:
    user:
      name: bokieureka
      password: 123456



eureka:
  instance:
    instance-id: boki-eureka
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/
    fetch-registry: false
    registerWithEureka: false

