server:
  port: 8000

spring:
  application:
    name: boki-eureka

eureka:
  instance:
    hostname: localhost
#    hostname: boki-eureka
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false
    registerWithEureka: false
