server:
  port: 9000

dataservice:
  host: 192.168.0.9

eureka-server:
  host: localhost
  port: 8000
  name: bokieureka
  password: 123456


spring:
  application:
    name: boki-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource          # 当前数据库操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # 驱动包
    url: jdbc:mysql://${dataservice.host}:3306/boki_local?characterEncoding=utf8&serverTimezone=GMT%2b8&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                          # 最小连接数
      initial-size: 5                                      # 初始化连接数
      max-total: 5                                         # 最大连接数
  cache:
    type: redis
  redis:
    database: 0
    host: ${dataservice.host}
    port: 6379
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    cache: false
  mail:
    username: 2500259143@qq.com
    password: kkmcfiljavcpdjgg
    host: smtp.qq.com
    default-encoding: utf-8


mybatis:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/com/boki/bokiclient/dao/mapper/*Mapper.xml
  type-aliases-package: com.boki.bokiapi.entity

eureka:
  instance:
    instance-id: boki-client-9000
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka-server.name}:${eureka-server.password}@${eureka-server.host}:${eureka-server.port}/eureka/



logging:
  level:
    root: info
#  file:
#    name:
#    path: